#!/usr/bin/env ruby

require 'open-uri'
SOURCE = "https://www.powerlanguage.co.uk/wordle/main.c1506a22.js"
source = URI.open(SOURCE).readlines(chomp: true)
TARGETS = source.first.match(/La=\[([^\]]*)\]/)[1].scan(/\w+/)
GUESSES = TARGETS+source.first.match(/Ta=\[([^\]]*)\]/)[1].scan(/\w+/)
#GUESSES = TARGETS

KEY = %w/- o +/         # not match, wrong location, match
RKEY = Hash[KEY.each_with_index.to_a]

def key(n)
  a = n.to_s(3).each_char.to_a
  a = ["0"]*(5-a.length)+a
  a.map{|n| KEY[n.to_i]}.join('')
end

def rkey(s)
  s.each_char.inject(0){|a,v|a*3+RKEY[v]}
end

def feedback(guess, target)
  g=guess.each_char.to_a
  t = target.each_char.to_a
  5.times{|i|t[i]=g[i]=2 if g[i]==t[i]}
  5.times.reject{|i|g[i]==2}.each{|i| ti=t.index(g[i]);t[ti]=g[i]=1 if ti}
  5.times{|i| g[i]=0 unless g[i].is_a?(Integer)}
  g.map(&:to_s).join('').to_i(3)
end

if ARGV.length == 0
  puts "raise"
  exit
end
ARGV.each do |a|
  g,ks = a.split('=')
  unless /^\w{5}$/.match(g) && /^[-o+]{5}$/.match(ks)
    puts "format error"
    exit
  end
  k = rkey(ks)
  TARGETS.select!{|t| feedback(g,t)==k}
end

if TARGETS.length == 1
  puts TARGETS.first
  exit
end

maxbins = GUESSES.map do |g|
  bins=Array.new(3**5,0)
  TARGETS.each{|t|bins[feedback(g,t)]+=1}
  [g,bins.max]
end

guess1 =  maxbins.sort_by{|_,a|a}.first[0]

puts guess1
